# Generated by Django 4.2 on 2025-01-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('A', 'Acción'), ('F', 'Ciencia Ficción'), ('N', 'Animada'), ('R', 'Romance'), ('I', 'Intriga'), ('H', 'Horror'), ('T', 'Terror'), ('C', 'Comedia'), ('B', 'Basada en hechos reales')], max_length=30)),
                ('director_name', models.CharField(max_length=30)),
                ('old', models.DateField()),
                ('synopsis', models.TextField(max_length=200)),
            ],
        ),
    ]
